# .gitpod.yml
# Gitpod workspace setup for Security Header Analyzer

tasks:
  - name: Setup Env and Tools
    init: |
      # --- Restore SSH private key from Gitpod env vars ---
      mkdir -p ~/.ssh
      echo "$ssh_private_key" > ~/.ssh/gitpod-key2
      chmod 600 ~/.ssh/gitpod-key2

      # --- Generate .env from Gitpod env vars ---
      echo "SECRET_KEY=${SECRET_KEY}" > .env
      echo "JWT_ALGORITHM=${JWT_ALGORITHM}" >> .env
      echo "ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}" >> .env
      echo "DATABASE_URL=${DATABASE_URL}" >> .env

      # --- Install AWS CLI v2 ---
      if ! command -v aws &> /dev/null; then
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
      fi

      # --- Install Terraform ---
      if ! command -v terraform &> /dev/null; then
        curl -fsSL https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip -o terraform.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
      fi

ports:
  - port: 8000
    onOpen: open-preview





